name: tara_voice_assistant
description: A simple hands‑free voice controller for phone, WhatsApp & Google Pay
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  speech_to_text: ^7.0.0
  flutter_tts: ^4.0.2
  url_launcher: ^6.3.1
  flutter_contacts: ^1.1.9+2
  permission_handler: ^11.3.0
  camera: ^0.10.0+4
  path_provider: ^2.0.15
  path: ^1.8.3
  flutter_local_notifications: ^12.0.4
  timezone: ^0.9.1

flutter:
  uses-material-design: true


